"use client"

import { useEffect, useState } from "react"
import supabase from "@/lib/supabase"
import { PickupCalendar } from "./PickupCalendar"
import { PickupHistory } from "./PickupHistory"
import { CustomerInfo } from "./CustomerInfo"
import { PickupStats } from "./PickupStats"
import { BookingDialog } from "./BookingDialog"
import { EditDialog } from "./EditDialog"

// ======================
// TYPES
// ======================
export interface PickupSchedule {
  id: string                // pickup_code (generated by DB)
  date: string
  timeSlot: string
  status: "confirmed" | "cancelled" | "completed"
  customerName: string
  customerPhone: string
  customerEmail: string
  pickupAddress: string
  parcelDetails: string
  specialInstructions?: string
  queueNumber?: string      // Q-001 (per day & time slot)
  createdAt: string
  updatedAt: string
}

interface PickupSchedulingProps {
  isBookingDialogOpen?: boolean
  onBookingDialogChange?: (open: boolean) => void
}

// ======================
// COMPONENT
// ======================
export function PickupScheduling({
  isBookingDialogOpen = false,
  onBookingDialogChange,
}: PickupSchedulingProps) {
  const [pickupHistory, setPickupHistory] = useState<PickupSchedule[]>([])
  const [selectedDate, setSelectedDate] = useState("")
  const [selectedTimeSlot, setSelectedTimeSlot] = useState("")
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [editingPickup, setEditingPickup] = useState<PickupSchedule | null>(null)

  // 🔄 Refresh key (auto refresh calendar & history)
  const [refreshKey, setRefreshKey] = useState(0)

  // ======================
  // LOAD PICKUP HISTORY
  // ======================
  useEffect(() => {
    let active = true

    const loadPickups = async () => {
      const { data, error } = await supabase
        .from("pickup_bookings")
        .select("*")
        .order("created_at", { ascending: false })

      if (error || !active) {
        console.error("Failed to load pickups:", error)
        return
      }

      const formatted: PickupSchedule[] = data.map((p) => ({
        id: p.pickup_code,
        date: p.pickup_date,
        timeSlot: p.time_slot,
        status: p.status,
        customerName: p.customer_name,
        customerPhone: p.customer_phone,
        customerEmail: p.customer_email,
        pickupAddress: p.pickup_address,
        parcelDetails: p.parcel_details,
        specialInstructions: p.special_instructions,
        queueNumber: p.queue_number,
        createdAt: p.created_at,
        updatedAt: p.updated_at,
      }))

      setPickupHistory(formatted)
    }

    loadPickups()

    return () => {
      active = false
    }
  }, [refreshKey])

  // ======================
  // CONFIRM BOOKING (QUEUE + SLOT SAFE)
  // ======================
  const handleNewBooking = async (newPickup: PickupSchedule) => {
    const { error } = await supabase.rpc("book_pickup_confirmed", {
      p_date: newPickup.date,
      p_time_slot: newPickup.timeSlot,
      p_customer_name: newPickup.customerName,
      p_customer_phone: newPickup.customerPhone,
      p_customer_email: newPickup.customerEmail,
      p_pickup_address: newPickup.pickupAddress,
      p_parcel_details: newPickup.parcelDetails,
      p_special_instructions: newPickup.specialInstructions,
    })

    if (error) {
      alert(
        "This slot was just taken by another customer. Please select a different time."
      )
      return
    }

    // 🔄 Refresh everything
    setRefreshKey((prev) => prev + 1)
    setSelectedTimeSlot("")
    onBookingDialogChange?.(false)
  }

  // ======================
  // EDIT BOOKING
  // ======================
  const handleEditBooking = async (updatedPickup: PickupSchedule) => {
    const { error } = await supabase
      .from("pickup_bookings")
      .update({
        pickup_date: updatedPickup.date,
        time_slot: updatedPickup.timeSlot,
        pickup_address: updatedPickup.pickupAddress,
        parcel_details: updatedPickup.parcelDetails,
        special_instructions: updatedPickup.specialInstructions,
        updated_at: new Date().toISOString(),
      })
      .eq("pickup_code", updatedPickup.id)

    if (error) {
      alert("Failed to update booking")
      return
    }

    setIsEditDialogOpen(false)
    setEditingPickup(null)
    setRefreshKey((prev) => prev + 1)
  }

  // ======================
  // CANCEL BOOKING
  // ======================
  const handleCancelBooking = async (pickupId: string) => {
    if (!confirm("Are you sure you want to cancel this pickup?")) return

    const { error } = await supabase
      .from("pickup_bookings")
      .update({
        status: "cancelled",
        updated_at: new Date().toISOString(),
      })
      .eq("pickup_code", pickupId)

    if (error) {
      alert("Failed to cancel booking")
      return
    }

    setRefreshKey((prev) => prev + 1)
  }

  // ======================
  // OPEN BOOKING DIALOG
  // ======================
  const handleOpenBookingDialog = () => {
    onBookingDialogChange?.(true)
  }

  // ======================
  // UI (UNCHANGED)
  // ======================
  return (
    <>
      <main className="min-h-screen bg-gray-50/50">
        <div className="p-4 md:p-6">
          {/* STATS */}
          <div className="mb-6 grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-white p-4 rounded-lg border shadow-sm">
              <div className="text-sm text-gray-500">Total Pickups</div>
              <div className="text-2xl font-bold">{pickupHistory.length}</div>
            </div>
            <div className="bg-white p-4 rounded-lg border shadow-sm">
              <div className="text-sm text-gray-500">Upcoming</div>
              <div className="text-2xl font-bold text-blue-600">
                {pickupHistory.filter(p => p.status === "confirmed").length}
              </div>
            </div>
            <div className="bg-white p-4 rounded-lg border shadow-sm">
              <div className="text-sm text-gray-500">Completed</div>
              <div className="text-2xl font-bold text-green-600">
                {pickupHistory.filter(p => p.status === "completed").length}
              </div>
            </div>
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            {/* LEFT */}
            <div className="lg:col-span-2 space-y-6">
              <PickupCalendar
                selectedDate={selectedDate}
                selectedTimeSlot={selectedTimeSlot}
                onDateSelect={setSelectedDate}
                onTimeSlotSelect={setSelectedTimeSlot}
                onBookingOpen={handleOpenBookingDialog}
                refreshKey={refreshKey}
              />

              <PickupHistory
                pickups={pickupHistory}
                onEdit={(pickup) => {
                  setEditingPickup(pickup)
                  setIsEditDialogOpen(true)
                }}
                onCancel={handleCancelBooking}
                onReschedule={(pickup) => {
                  setSelectedDate(pickup.date)
                  setSelectedTimeSlot(pickup.timeSlot)
                  onBookingDialogChange?.(true)
                }}
              />
            </div>

            {/* RIGHT */}
            <div className="space-y-6">
              <CustomerInfo />
              <PickupStats pickups={pickupHistory} />
            </div>
          </div>
        </div>

        {/* DIALOGS */}
        <BookingDialog
          isOpen={isBookingDialogOpen}
          onOpenChange={onBookingDialogChange || (() => {})}
          selectedDate={selectedDate}
          selectedTimeSlot={selectedTimeSlot}
          onBook={handleNewBooking}
        />

        <EditDialog
          isOpen={isEditDialogOpen}
          onOpenChange={setIsEditDialogOpen}
          pickup={editingPickup}
          onSave={handleEditBooking}
        />
      </main>
    </>
  )
}
